//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KreiranjeDogadaja
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipKarte
    {
        public int id { get; set; }
        public Nullable<int> iznosPopusta { get; set; }
        public string naziv { get; set; }
        public Nullable<int> CjenikDogadajaid { get; set; }
    
        public virtual CjenikDogadaja CjenikDogadaja { get; set; }
    }
}
