//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvidencijaOrganizatora
{
    using System;
    using System.Collections.Generic;
    
    public partial class tse_dog_org
    {
        public int Dogadajid { get; set; }
        public int Organizatorid { get; set; }
    
        public virtual Dogadaj Dogadaj { get; set; }
        public virtual Organizator Organizator { get; set; }
    }
}
