//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdajaKarata
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Racun()
        {
            this.Uslugas = new HashSet<Usluga>();
        }
    
        public int id { get; set; }
        public string operater { get; set; }
        public Nullable<System.DateTime> vrijeme { get; set; }
        public Nullable<double> ukupno { get; set; }
        public string nazivKupca { get; set; }
        public Nullable<int> Zaposlenikid { get; set; }
        public Nullable<int> Dogadajid { get; set; }
    
        public virtual Dogadaj Dogadaj { get; set; }
        public virtual Zaposlenik Zaposlenik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usluga> Uslugas { get; set; }
    }
}
